# -*- coding: utf-8 -*-
"""randomNumberGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBX5Wg9bPzQYnJfmwlYk_1JzIiijBzdn
"""

# random number generator

import random

print(random.randint(a,b))